name: Run PowerShell Script
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0/3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PowerShell script
        shell: pwsh
        run: .\run1.ps1
