name: Run PowerShell Script
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yt-dlp
        run: |
          # 下載 yt-dlp.exe 到 .github/workflows 目錄
          Invoke-WebRequest -Uri 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe' -OutFile '.github/workflows/yt-dlp.exe'
      - name: Run PowerShell script
        shell: pwsh
        run: .\run1.ps1
